name: fedifetcher
services:
  fedifetcher:
    stdin_open: true
    tty: true
    image: ghcr.io/nanos/fedifetcher:latest
    command: "--access-token=<TOKEN> --server=<SERVER>"
    # Persist our data
    volumes:
      - ./data:/app/artifacts
    # Use the `deploy` option to enable `restart_policy`
    deploy:
      # Don't go above 1 replica to avoid multiple overlapping executions of the script
      replicas: 1
      restart_policy:
        # The `any` condition means even after successful runs, we'll restart the script
        condition: any
        # Specify how often the script should run - for example; after 1 hour.
        delay: 1h